
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: Promise<React.ReactNode>
}) {
  return (
    <>{await children}</>
  )
}
