import { TrpcProvider } from "./TrpcProvider";
import '../styles/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export { reportWebVitals } from 'next-axiom';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><TrpcProvider>{children}</TrpcProvider></body>
    </html>
  )
}
